apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
subsets:
  - addresses:
      - ip: 192.168.178.30
    ports:
      - port: 32400
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  name: plex
spec:
  rules:
  - host: plex.terrible.systems
    http:
      paths:
      - backend:
          service:
            name: plex
            port:
              number: 32400
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - plex.terrible.systems
    secretName: plex-tls-cert
