apiVersion: v1
kind: Service
metadata:
  name: nixcache
spec:
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nixcache
subsets:
  - addresses:
      - ip: 192.168.178.105
    ports:
      - port: 9003
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/frontend-entry-points: http, https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  name: nixcache
spec:
  rules:
  - host: nixcache.infra.terrible.systems
    http:
      paths:
      - backend:
          service:
            name: nixcache
            port:
              number: 9003
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nixcache.infra.terrible.systems
    secretName: nixcache-tls-cert
