---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athens
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://athens.blob.core.windows.net/charts/
      chart: athens-proxy
      version: 0.5.2
      sourceRef:
        kind: HelmRepository
        name: athens-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/frontend-entry-points: http, https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - goproxy.hormonal.party
      tls:
      - hosts:
        - goproxy.hormonal.party
        secretName: goproxy-tls-cert
    storage:
      disk:
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 4Gi
          storageClass: "local-path"
    jaeger:
      enabled: false
    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 250Mi
    upstreamProxy:
      enabled: false # Disabled to see if we get a noticable improvement from
                     # caching everything locally
      url: "https://proxy.golang.org"
