---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: athens
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://athens.blob.core.windows.net/charts/
      chart: athens-proxy
      version: 0.4.15
      sourceRef:
        kind: HelmRepository
        name: athens-charts
        namespace: flux-system
      interval: 5m
  values:
    service:
      type: NodePort
      nodePort:
        port: 30001
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClass: "local-path"
    resources:
      limits:
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 250Mi
    upstreamProxy:
      enabled: true
      url: "https://proxy.golang.org"
