---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.2.0
    env:
      TZ: "Europe/Berlin"

    # Host Networking is required for device discovery with home-assistant.
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet

    # This service is actually kind of pointless but means that the ingress gets
    # created properly and I don't want to keep messing with it.
    service:
      enabled: true
      type: LoadBalancer
      port:
        port: 8081
        targetPort: 8123

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
      - host: homeassistant.hormonal.party
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "homeassistant.hormonal.party"
        secretName: homeassistant-tls-cert

    # TODO: Enable git support and/or mount this from nfs when we setup nfs CSI
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: "10Gi"

    # Store history in a dedicated postgres - The data is non-essential so local
    # is fine.
    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true
        storageClass: "local-path"

    # TODO: setup monitoring
    prometheus:
      serviceMonitor:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true

    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 100m
        memory: 1000Mi
