---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
  namespace: default
spec:
  releaseName: photoprism
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: photoprism/photoprism
      tag: "20210211"
    env:
      PHOTOPRISM_SITE_URL: "https://photos.hormonal.party"
      PHOTOPRISM_SITE_TITLE: "Photos"
      PHOTOPRISM_SITE_AUTHOR: "@endocrimes"
      PHOTOPRISM_ADMIN_PASSWORD: "photoprism"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
      - host: photos.hormonal.party
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - photos.hormonal.party
        secretName: photoprism-cert
    persistence:
      config:
        enabled: true
      originals:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
