---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pictures-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-pictures-pvc
  storageClassName: ""
  nfs:
    server: 192.168.178.105
    path: "/spool/home/danielle"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pictures-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-pictures-pv
  resources:
    requests:
      storage: 1Mi
---
